name: costv_android
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  event_bus: ^1.1.0
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.3
  dio: ^3.0.7
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  common_utils: ^1.1.3
  flustars: ^0.2.6+1
  device_info: ^0.4.1+1
  cached_network_image: ^2.0.0
  image_picker: ^0.6.2+3
  url_launcher: ^5.4.1
  sqflite: ^1.1.8
  package_info: ^0.4.0+13
  share: ^0.6.3+3
  video_player: ^0.10.5
  chewie:
    path: plugins/chewie
  permission_handler: ^4.0.0
  sensors_analytics_flutter_plugin: ^1.0.1
  encrypt: ^3.3.1
  get_ip: ^0.3.0
  flutter_html: ^0.11.0
  flutter_slidable: ^0.5.4
  flutter_datetime_picker: ^1.3.1
  firebase_core: ^0.4.3+2
  firebase_analytics: ^5.0.9
  auto_size_text: ^2.1.0
  wakelock: ^0.1.3+3
  cosdart:
    git:
      url: git://github.com/coschain/cosdart.git
      ref: master

  webview_flutter_fix:
    path: plugins/webview_flutter_fix

dev_dependencies:
  flutter_test:
    sdk: flutter
  #json序列化相关
  build_runner: 1.7.1
  json_serializable: 3.2.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/bg_label.png
    - assets/images/bg_play_avatar_gold.png
    - assets/images/bg_play_avatar_silver.png
    - assets/images/bg_startup_diagram.png
    - assets/images/bg_top_avatar_gold.png
    - assets/images/bg_top_personal_information.png
    - assets/images/bg_triangle_white.png
    - assets/images/ic_attention.png
    - assets/images/ic_attention_all_finish.png
    - assets/images/ic_attention_finish.png
    - assets/images/ic_back.png
    - assets/images/ic_back_white.png
    - assets/images/ic_champion.png
    - assets/images/ic_close_black.png
    - assets/images/ic_comment_first.png
    - assets/images/ic_comment_heart.png
    - assets/images/ic_comment_like_no.png
    - assets/images/ic_comment_like_yes.png
    - assets/images/ic_default_avatar.png
    - assets/images/ic_down_money.png
    - assets/images/ic_down_title.png
    - assets/images/ic_gift.png
    - assets/images/ic_gift_count.png
    - assets/images/ic_gift_light.png
    - assets/images/ic_home.png
    - assets/images/ic_home_select.png
    - assets/images/ic_hot_cute_pets.png
    - assets/images/ic_hot_fun.png
    - assets/images/ic_hot_game.png
    - assets/images/ic_hot_music.png
    - assets/images/ic_input_close.png
    - assets/images/ic_logo.png
    - assets/images/ic_menu.png
    - assets/images/ic_my_subscription.png
    - assets/images/ic_my_subscription_select.png
    - assets/images/ic_play_avatar_gold.png
    - assets/images/ic_play_avatar_silver.png
    - assets/images/ic_play_count.png
    - assets/images/ic_play_gift.png
    - assets/images/ic_pop_number.png
    - assets/images/ic_popular.png
    - assets/images/ic_popular_select.png
    - assets/images/ic_release_time.png
    - assets/images/ic_report.png
    - assets/images/ic_right_comment.png
    - assets/images/ic_right_gift.png
    - assets/images/ic_runner_up.png
    - assets/images/ic_search.png
    - assets/images/ic_search_history_delete.png
    - assets/images/ic_search_no_data.png
    - assets/images/ic_search_replace.png
    - assets/images/ic_see_history.png
    - assets/images/ic_see_history_select.png
    - assets/images/ic_share.png
    - assets/images/ic_third.png
    - assets/images/ic_title.png
    - assets/images/ic_title_default_avatar.png
    - assets/images/ic_title_logo.png
    - assets/images/ic_title_pop.png
    - assets/images/ic_title_search.png
    - assets/images/ic_top_close.png
    - assets/images/ic_top_gift.png
    - assets/images/ic_top_more_msg.png
    - assets/images/ic_update_app_top_bg.png
    - assets/images/ic_video_like_no.png
    - assets/images/ic_video_like_yes.png
    - assets/images/ic_hot_fun.png
    - assets/images/ic_hot_game.png
    - assets/images/ic_hot_music.png
    - assets/images/ic_hot_cute_pets.png
    - assets/images/ic_watch_history.png
    - assets/images/ic_liked.png
    - assets/images/ic_gift_ticket_reward.png
    - assets/images/ic_delete.png
    - assets/images/img_request_fail.png
    - assets/images/img_subscription_remind.png
    - assets/images/img_watch_history_remind.png
    - assets/images/ic_history_more.png
    - assets/images/ic_watch_feedback.png
    - assets/images/player_play.png
    - assets/images/player_pause.png
    - assets/images/player_prev.png
    - assets/images/player_next.png
    - assets/images/player_replay.png
    - assets/images/player_enter_fullscreen.png
    - assets/images/player_fullscreen_exit.png
    - assets/images/player_fullscreen_lock.png
    - assets/images/player_fullscreen_pause.png
    - assets/images/player_fullscreen_play.png
    - assets/images/player_fullscreen_replay.png
    - assets/images/player_fullscreen_unlock.png
    - assets/images/img_subscription_projection.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
